# Generated by Django 3.2.8 on 2021-12-17 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['id']},
        ),
    ]
