# Generated by Django 3.2.8 on 2021-12-18 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments_service', '0002_alter_patient_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentdate',
            name='is_free',
        ),
        migrations.AddField(
            model_name='appointmentdate',
            name='doctor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_dates', to='appointments_service.doctor'),
        ),
    ]
