# Generated by Django 3.2.8 on 2021-12-18 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments_service', '0003_auto_20211218_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentdate',
            name='doctor',
        ),
    ]
