# Generated by Django 3.2.8 on 2021-12-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments_service', '0004_remove_appointmentdate_doctor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmentdate',
            options={'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='appointmentdate',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='appointmentdate',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='appointmentdate',
            name='date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
